apiVersion: config.geist-iot.com/v1alpha
kind: GeistConnector
metadata:
  # Name of this specific instance
  name: geist-connector-example
  # Namespace where this resource will be created
  namespace: geist
spec:
  deploymentSpec:
      customLabels:
        app: geist-connector
      customAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
  connectorSpec:
    opcua:
      connection:
        authentication:
          type: None
        certificate:
          auto_create: false
          external_certificate: false
          certificate: | 
            -----BEGIN CERTIFICATE-----
            MIIDGDCCAgCgAwIBAgIBATANBgkqhkiG9w0BAQsFADAlMQswCQYDVQQGEwJERTEW
            MBQGA1UECgwNR2Vpc3RARGVza3RvcDAeFw0yNTEwMTIxOTA3NTZaFw0zNTEwMTAx
            OTA3NTZaMCUxCzAJBgNVBAYTAkRFMRYwFAYDVQQKDA1HZWlzdEBEZXNrdG9wMIIB
            IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwNoVY2Hrz5dYmsheFdrdqAtT
            2O7fw5xBW4z+VFVaKiYr4P7mivVlQgfPsRrd2cKkSnbFj+Q/QOr2ZAkYxovEKSvq
            taBMAX1TP0sr04GX3kp2B6MyAaDUkwdVnv7S8SAhfiUoTHb/VO3aF2NBPGwDTOlw
            ToXpwSutUFnFqbYnS3a+FlUfFkC7+PRce0qGGh4hqn7S5BmQ11yR9WkHXdjqAv/+
            LvpFU0/P8RkYZA28k/dUhtjgxT4ICZX19Lx2R5c/eN1trnlgN7J+f3ri/YR0Ng1z
            wd16rBTrdER1OrnUCeNlExQoSXCa2yrmLQDO7vKuomiRiyH/6kApnZERT06k9QID
            AQABo1MwUTAOBgNVHQ8BAf8EBAMCAvQwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsG
            AQUFBwMBMAwGA1UdEwEB/wQCMAAwEgYDVR0RBAswCYYHRGVza3RvcDANBgkqhkiG
            9w0BAQsFAAOCAQEAgq6x0+xxdGFZknVHttFHjyyDEdwdn3nMe1ZdSvH0iL7Rqabf
            N0WYjuOjX+C1g67cWuNw56/Lz6O7Gs/qMHUGhr1fRLyt2NWPlrRbe28sureJqXu4
            RSRM4JUwYvD8HLjRE8g74a5jbFbmkHvJJuAoTwb7BGk2Cglgdhj9p9a1hfaN59rM
            D47h/FGv5BC1MtR+H7jheRJ3qGL/k9Xx1A2FvqHvR8JADDYeRNNG44RB/8Dx1r3K
            dBbkZyNfUPAoO1+wPhOTDQ4g5PywolViQ/hpzjrPWbufeDlKvTB4kdMPclRpwLkJ
            I0eBxYGsQ+Kvfb0mkjYMcVwWM37Jyex5Ls8GMQ==
            -----END CERTIFICATE-----
          private_key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEAwNoVY2Hrz5dYmsheFdrdqAtT2O7fw5xBW4z+VFVaKiYr4P7m
            ivVlQgfPsRrd2cKkSnbFj+Q/QOr2ZAkYxovEKSvqtaBMAX1TP0sr04GX3kp2B6My
            AaDUkwdVnv7S8SAhfiUoTHb/VO3aF2NBPGwDTOlwToXpwSutUFnFqbYnS3a+FlUf
            FkC7+PRce0qGGh4hqn7S5BmQ11yR9WkHXdjqAv/+LvpFU0/P8RkYZA28k/dUhtjg
            xT4ICZX19Lx2R5c/eN1trnlgN7J+f3ri/YR0Ng1zwd16rBTrdER1OrnUCeNlExQo
            SXCa2yrmLQDO7vKuomiRiyH/6kApnZERT06k9QIDAQABAoIBAAhs7r7JDiujZdpb
            Uyr6xTDcj9T8OLf72Wolyo3GLdqGEOgzUsCy8HHWVAddkGA9bf6X2lFLTE0qhsm/
            kP7Jp/ARjF9TicaN4mdzQg6rTIaIc8gpI9vo2iizSxUXdoFU4Um4114h281q19qq
            OjUo1esUDtVLafdH0Hpgda+Qtv5HtiIn/R9b6QCZyUwIm5cpK4HYkXU9csw5aPQV
            eelPZ25b/miN9PdWBz1lF6tSVBFcg8Z6IYzGcnuGOtjMQBHokV3j8wU5pltls/R5
            iJ3O0pSfTNpOUfGm2+qpVjmpIPXbmEmzJHZMNe5mzxq42Rv9hd7ouqbTj0QZV8L7
            FybRMmkCgYEA2P8urPb9JSZfqsU7fY4UYXFeusaSXOjgsPYqMFlo1C1GeRH+5+CH
            2NdIHV/IvVOFIYXfE2OIzMbx1EnQN592gwoV8XYm5bGXW935gRL8i7CDlLrdcy8c
            Bmz4/iLegDv9P9ioyL7pUj9jaasaa+QFqAxEpVPlZC4WK6CrTcvuSJ0CgYEA44Pn
            uQ8wmibvRke23Xj+OXXODoViirW2iZ9tgwOxwcRXZGKfAPkvfnNOqU38w7uwWToS
            XW2Cml8fCRmf7HnNP436HvkpdHZR6VOE/tIPh3kky/OPghe2Qa03C5+6AwCRCZjL
            9wzCaDoUG/ckQCSYxTChRL96HQdHtfCpZqAoQjkCgYA8T5iCfFdZhvPZ+92QBPhH
            KQJiOSSe7B7fMFwDeiY3qqnGpqjJe89mBlfFykR50ofTDGk281gnSjgWf7l+bDS9
            MQVuSh9/gb+Gygg5xrQogxPfN5yrEfHhG1KNF9XtoD7ACxDGUsF4maOgz+yVBhhI
            X7iIluvPzztcPti906tTxQKBgQDW3WrJHexTmPOeVvn/PVYyY+w/UH8Y6rXCUTt2
            YNXOXiP+nRj3LV5KOJGQWSOeorHQAoT3kQWnzq+bw4SCKyHIpMgT2lHpOBjxlzvh
            //ZEhgdXSeU9AjHQ4so6gxWD4lQXUSNHZNhw4HC/XG7y2N0iVWPobkDgC1ERJYCG
            eDitGQKBgQDBq36LD0hGyfkAw7u+N+GR82Gz9KHY+UYZQ0EitZAmiBaVpXq70w6F
            oGwTsSZ6Qmt4hqyRobwPAgr3b9QT+oHkvAbiwJ6/FavwW4MEYvoNbwz0ChCIvWlb
            ztSlrH29J+WPM6lLwPiWG9qGN1xJ7wMpu3/lUsTVcqtt3hepI87O/Q==
            -----END RSA PRIVATE KEY-----
        endpoint: 192.168.178.146
        mode: SignAndEncrypt
        policy: Basic256Sha256
        port: 49320
        retry_count: 10
      subscription:
        nodeids:
        - id: ns=2;s=Machines.Packaging.Tag1
        - id: ns=2;s=Machines.Packaging.Tag2
        sub_interval: 1
    redpanda:
        brokers:
          - redpanda.geist.svc.cluster.local:9093
        topic: geist-topic
        tls:
          insecure_skip_verify: true # set to true to ignore self-signed certificates